
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=n
CONFIG_LOG_PRINTK=y
CONFIG_LOG=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=n
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DIS=n
CONFIG_BT_BAS=n
CONFIG_BT_DEVICE_NAME="Free Pad"
CONFIG_BT_DEVICE_APPEARANCE=964

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_BT_SMP_SC_PAIR_ONLY=y
CONFIG_BT_MAX_PAIRED=1
CONFIG_BT_SMP=y

CONFIG_BT_GATT_SERVICE_CHANGED=n
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=300

CONFIG_GPIO=y
# CONFIG_USB_CDC_ACM_LOG_LEVEL_OFF=y
# CONFIG_NVS_LOG_LEVEL_OFF=y

CONFIG_WDT_LOG_LEVEL_OFF=y
CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=y
